src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("comment:read")]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups("comment:read")]
    private ?Trick $trick = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups("comment:read")]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups("comment:read")]
    private ?string $comment = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups("comment:read")]
    private ?\DateTimeInterface $created_date = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, [
                'label' => 'Nom',
                'empty_data' => ''
            ])
            ->add('description', null, [
                'label' => 'Description',
                'empty_data' => ''
            ])
            ->add(
                'categories',
                EntityType::class,
                [
                    'class' => Category::class,
                    'label' => 'Catégories',
                    'choice_label' => 'name',
                    'expanded' => true,
                    'multiple' => true,
                    'query_builder' => function (EntityRepository $er) {
                        return $er->createQueryBuilder('c')->orderBy('c.name', 'ASC');
                    },
                    'by_reference' => false // Pour que le choix des catégories soit enregistré en base (en même temps que le trick via le flush dans notre TrickController), il faudrait que Symfony puisse faire $trick->setCategory() or dans l'entité Trick qui est en ManyToMany avec category il n'y a pas de setCategory(). Par contre il y a un addCategory(). Le paramètre by_reference avec la valeur false indique à Doctrine que la relation entre l'entité parente et l'entité enfant doit être gérée en utilisant une collection de type PersistentCollection. Cela signifie que les changements apportés aux objets enfants de la collection seront automatiquement suivis par Doctrine et seront persistés en base de données. En fait il clone l'objet, ce qui oblige le framework à appeler le setter sur l'objet parent.
                ]
            )
            ->add('image', FileType::class, [
                'label' => false,
                'multiple' => true,
                'required' => false,
                'mapped' => false, // c une relation, ce champ n'est pas rempli dans la table Trick (il est dans la table Image) donc on doit mettre : mapped à false
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => VideoType::class,
                'entry_options' => ['label' => false, 'attr' => ['class' => 'video-url-input']],
                'required' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'label' => false,
                // 'prototype' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Image;
use App\Entity\Trick;
use App\Entity\Video;
use App\Form\CommentType;
use App\Form\TrickType;
use App\Repository\CommentRepository;
use App\Repository\TrickRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class TrickController extends AbstractController
{
    private $slugger;

    public function __construct(SluggerInterface $slugger)
    {
        $this->slugger = $slugger;
    }

    #[Route('/', name: 'trick_home')]
    public function home(TrickRepository $trickRepository, Request $request): Response
    {
        // On va chercher le numéro de page dans l'url :
        $currentPage = $request->query->getInt('page', 1);

        // On va chercher le tableau (liste des tricks + total de pages + limit) :
        $tricksPagination = $trickRepository->findTricksPaginated($currentPage, 4); // limit = 4

        return $this->render('trick/home.html.twig', [
            'tricksPagination' => $tricksPagination,
            'currentPage' => $currentPage,
        ]);
    }

    #[Route('/trick/creer', name: 'trick_new')]
    public function newTrick(Request $request, EntityManagerInterface $em): Response
    {
        // D'abord vérifier que l'utilisateur est authentifié
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $trick = new Trick();

        $form = $this->createForm(TrickType::class, $trick);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $trick = $form->getData();
            $trick->setCreatedDate(new \DateTime());
            $trick->setUpdatedDate(new \DateTime());
            $trick->setAuthor($this->getUser());
            $trick->setSlug($this->slugger->slug($trick->getName()));

            $this->importImages($trick, $form);

            $em->persist($trick);
            $em->flush();

            $this->addFlash('success', "Votre trick a été enregistré");

            return $this->redirectToRoute('trick_home');
        }

        return $this->render('trick/new.html.twig', [
            'formTrick' => $form->createView(), // Utilisez createView() pour le rendu du formulaire
        ]);
    }

    #[Route('/trick/{trickSlug}', name: 'trick_showOne')]
    public function showOneTrick(TrickRepository $trickRepository, CommentRepository $commentRepository, Request $request, EntityManagerInterface $em, $trickSlug): Response
    {
        // Récupération du trick associé au slug :
        $trick = $trickRepository->findOneBy(['slug' => $trickSlug]);
        if (!$trick) {
            throw new NotFoundHttpException("Pas de Trick trouvé"); // c'est pas redondant avec "Page non trouvée"?
        }

        // Formulaire du commentaire :
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
            $comment->setCreatedDate(new \DateTime());
            $comment->setTrick($trick);
            $comment->setUser($this->getUser());
            $em->persist($comment);
            $em->flush();

            return $this->redirectToRoute('trick_showOne', array('trickSlug' => $trick->getSlug()));
        }

        return $this->render('trick/show_one.html.twig', [
            'trick' => $trick,
            'trickSlug' => $trickSlug,
            'formComment' => $form,
        ]);
    }

    #[Route('/trick/{slug}/modifier', name: 'trick_edit')]
    public function editTrick(string $slug, Request $request, EntityManagerInterface $em): Response
    {
        $trick = $em->getRepository(Trick::class)->findOneBy(['slug' => $slug]);
        if (!$trick) {
            throw $this->createNotFoundException('Pas de Trick trouvé pour le slug ' . $slug);
        }

        // D'abord vérifier que l'utilisateur est authentifié
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        // Vérifie les autorisations avec le voter (a le droit de modifier s'il est l'auteur)
        $this->denyAccessUnlessGranted("TRICK_EDIT", $trick); // ok

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->importImages($trick, $form);

            $videos = $form->get('videos')->getData();

            foreach ($videos as $video) {
                // Associer la vidéo au trick
                $video->setTrick($trick);
            }

            $em->flush();
            return $this->redirectToRoute('trick_home');
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'formTrick' => $form->createView(),
        ]);
    }

    #[Route('/trick/{slug}/supprimer', name: 'trick_delete')]
    public function deleteTrick(string $slug, EntityManagerInterface $em): Response
    {
        $trick = $em->getRepository(Trick::class)->findOneBy(['slug' => $slug]);
        if (!$trick) {
            throw $this->createNotFoundException('No trick found for slug ' . $slug);
        }

        // D'abord vérifier que l'utilisateur est authentifié
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        // Vérifie les autorisations avec le voter (ok s'il est l'auteur)
        $this->denyAccessUnlessGranted("TRICK_DELETE", $trick);

        // On supprime physiquement les images :
        $images = $trick->getImages();
        // var_dump($images);
        if ($images) {
            foreach ($images as $image) {
                // on récupère le chemin :
                $nomImage = $this->getParameter("images_directory") . '/' . $image->getName();
                // on vérifie si l'image existe :
                if (file_exists($nomImage)) { // return true
                    // on la supprime :
                    unlink($nomImage);
                }
            }
        }
        $em->remove($trick);
        $em->flush();
        return $this->redirectToRoute('trick_home');
    }

    #[Route('/trick/{trickSlug}/commentaires', name: 'trick_getComments', methods: ["GET"])]
    // exemple: /trick/TestNom1/commentaires?page=3
    public function getComments(CommentRepository $commentRepository, Request $request, $trickSlug)
    {
        // On va chercher le numéro de page dans l'url :
        $currentPage = $request->query->getInt('page', 1);

        // On va chercher le tableau (liste des commentaires + total de pages + limit) :
        $commentsPagination = $commentRepository->findCommentsPaginated($trickSlug, $currentPage, 10); // limit est imposé à 10 par OC
        // dd($commentsPagination);

        return $this->json($commentsPagination, 200, [], ['groups' => 'comment:read']);
        // $this->json() utilise SerializerInterface
    }

    #[Route('/tricks/catégorie/{categorySlug}', name: 'trick_showByCategory')]
    public function showByCategory(TrickRepository $trickRepository, Request $request, $categorySlug): Response
    {
        // On va chercher le numéro de page dans l'url :
        $currentPage = $request->query->getInt('page', 1);

        // On va chercher le tableau (liste des tricks par catégorie + total de pages +limit) :
        $tricksPagination = $trickRepository->findTricksByCategoryPaginated($categorySlug, $currentPage, 3); // limit = 3

        return $this->render('trick/show_by_category.html.twig', [
            'tricksPagination' => $tricksPagination,
            'currentPage' => $currentPage,
            'categorySlug' => $categorySlug,
        ]);
    }

    #[Route('/tricks/suppression_image/{id}', name: 'trick_delete_image', methods: ['DELETE'])]
    public function deleteImage($id, Request $request, EntityManagerInterface $em): JsonResponse
    {
        $image = $em->getRepository(Image::class)->findOneBy(['id' => $id]);
        if (!$image) {
            throw $this->createNotFoundException('Aucune image trouvée pour l\'id ' . $id);
        }

        // On récupère le contenu de la requête json sous forme de tableau
        $data = json_decode($request->getContent(), true);

        // On vérifie si le jeton CSRF contenu dans le tableau associatif est valide en utilisant la méthode isCsrfTokenValid().
        // Lorsque le client envoie une requête au serveur, il doit inclure le jeton CSRF dans la requête pour prouver qu'il est bien un utilisateur autorisé et non un attaquant.
        // isCsrfTokenValid() prend 2 paramètres : la clé utilisée pour stocker le jeton CSRF dans la session du client, qui est générée en concaténant la chaîne "delete" avec l'ID de l'image à supprimer, et la valeur du jeton CSRF qui a été envoyée avec la requête HTTP.
        // isCsrfTokenValid() compare la valeur du jeton CSRF stockée dans la session avec la valeur envoyée dans la requête AJAX pour vérifier que l'utilisateur qui effectue la demande est autorisé à le faire. Icis, la clé utilisée pour stocker le jeton CSRF dans la session est générée en concaténant la chaîne "delete" avec l'ID de l'image à supprimer.
        if ($this->isCsrfTokenValid('delete' . $image->getId(), $data['_token'])) {
            // Si le token csrf est valide:
            // On supprimer le fichier de l'image
            $imagePath = $this->getParameter('images_directory') . '/' . $image->getName();
            if (file_exists($imagePath)) {
                unlink($imagePath);
            }

            // On supprime l'image de la base de données
            $em->remove($image);

templates/trick/home.html.twig
{% extends 'base.html.twig' %}
{% block title %}Liste de Tricks{% endblock %}

{% block body %}
	<div class="row mt-4">
		{% for trick in tricksPagination.tricksPerPage %}
			<div class="col-12 col-md-6 col-lg-3 mb-3" style="margin-top: 84px;">
				<div class="card h-100">
					<div class="card-body">
						<h2 class="card-title text-truncate" style="font-size: 1.5rem; line-height: 1.2; margin-bottom: 10px;">{{ trick.name }}</h2>

						{% if trick.getImages() is not empty %}
							<img src="{{ asset('/uploads/images/' ~ trick.getImages() | first.name) }}" alt="Image" class="card-img-top">
						{% else %}
							{# <img src="{{ asset('/path/to/placeholder-image.jpg') }}" alt="Placeholder Image" class="card-img-top"> #}
						{% endif %}

						<p style="color: #8c959e; margin-bottom: 16px; margin-top: 10px;">
							<span style="margin-bottom: 1.5em;"><i class="fa fa-calendar"></i> {{ trick.createdDate| date('d/m/Y') }} à {{ trick.createdDate | date('h:m') }}</span>
							<span style="margin-bottom: 1.5em;"><img src="{{trick.author.avatar}}" class="rounded-circle" height="24" width="24"/> {{ trick.author.username }}</span>
						</p>

						<div style="margin-bottom: 16px;">
							{% if trick.categories %}
								{% for category in trick.categories %}
									<a href="{{ path('trick_showByCategory', {'categorySlug': category.slug}) }}" title="Voir les tricks de cette catégorie" style="margin-right: 5px;">
										<i class="fa fa-tag"></i> {{ category.name }}
									</a>
								{% endfor %}
							{% endif %}
						</div>

						<div class="card-text text-truncate lire-suite">
							<p>{{ trick.description | raw }}</p>
							<a href="{{ path('trick_showOne', {'trickSlug':trick.slug}) }}" class="btn btn-primary btn-custom">Voir ce Trick</a>
						</div>

						<div style="color: #8c959e; margin-bottom: 10px; margin-top: 10px;">
							{{ trick.comments.count() }}
							{% if trick.comments.count() > 1 %} commentaires
							{% else %} commentaire
							{% endif %}
						</div>

					</div>
				</div>
			</div>
		{% endfor %}

		{% set path = 'trick_home' %}
		{% set param1 = {'page':currentPage-1} %}
		{% set param2 = {'page':currentPage} %}
		{% set param3 = {'page':currentPage+1} %}
		{% set totalOfPages = tricksPagination.totalOfPages %}
		{% set currentPage = currentPage %}
		<div class="">
			{% include "_partials/_pagination.html.twig" %}
		</div>
	</div>
{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de Tricks
{% endblock %}

{% block body %}
	<section class="trick">
		{% for trick in tricks %}
			<article>
				<h2>{{ trick.name }}</h2>
				<div class="metadata">Ecrit le
					{{ trick.createdDate | date('d/m/Y') }}
					à
					{{ trick.createdDate | date('h:m') }}
				</div>
				<div class="content">
					<p>{{ trick.description | raw }}</p>
					<a href="{{ path('trick_showOne', {'slug':trick.slug}) }}" class="btn btn-primary">Lire la suite</a>
				</div>
			</article>
		{% endfor %}
	</section>
{% endblock %}

templates/trick/new&edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme formTrick 'bootstrap_5_layout.html.twig' %}
{% block title %}
	{% if editMode %}
		Mise à jour d'un Trick
	{% else %}
		Creation d'un Trick
	{% endif %}
{% endblock %}

{% block body %}
	{% if editMode %}
		<h1>Mise à jour d'un Trick</h1>
	{% else %}
		<h1>Creation d'un Trick</h1>
	{% endif %}
	{{ form_start(formTrick, {'attr': {'novalidate': 'novalidate'}}) }}

	{{ form_row(formTrick.name, {'attr' : {'placeholder' : "Nom" }}) }}

	{{ form_row(formTrick.description, {'attr' : {'placeholder' : "Description" }}) }}

	<button type="submit" class="btn btn-success">
		{% if editMode %}
			Modifier le Trick
		{% else %}
			Créer le Trick
		{% endif %}
	</button>
	{{ form_end(formTrick) }}
{% endblock %}

templates/trick/showAll.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de Tricks
{% endblock %}

{% block body %}
	<p>Liste de Tricks</p>
	<div class="row">
		{% for trick in tricksPagination.tricksPerPage %}
			<div class="col-3 mb-3">
				<div class="border border-dark rounded p-2 h-100">
					<h2>{{ trick.name }}</h2>
					<div class="content">Ecrit le
						{{ trick.createdDate | date('d/m/Y') }}
						à
						{{ trick.createdDate | date('h:m') }}
						par
						{{ trick.author.username }}
					</div>
					<div>
						{% if trick.categories %}
							{% for category in trick.categories %}
								<a href="{{ path('trick_showByCategory', {'categorySlug': category.slug}) }}">{{ category.name }}</a>
							{% endfor %}
						{% endif %}
					</div>
					<div class="content">
						<p>{{ trick.description | raw }}</p>
						<a href="{{ path('trick_showOne', {'trickSlug':trick.slug}) }}" class="btn btn-primary">Lire la suite</a>
					</div>
				</div>
			</div>
		{% endfor %}

		{% set path = 'trick_showAll' %}
		{% set param1 = {'page':currentPage-1} %}
		{% set param2 = {'page':currentPage} %}
		{% set param3 = {'page':currentPage+1} %}
		{% set totalOfPages = tricksPagination.totalOfPages %}
		{% set currentPage = currentPage %}
		<div class=""></br>
		{% include "_partials/_pagination.html.twig" %}
	</div>
</div>{% endblock %}

templates/trick/showByCategory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de Tricks
{% endblock %}

{% block body %}
	<p>Liste de Tricks</p>
	<div class="row">
		{% for trick in tricksPagination.tricksPerPage %}
			<div class="col-3 mb-3">
				<div class="border border-dark rounded p-2">
					<h2>{{ trick.name }}</h2>
					<div class="content">Ecrit le
						{{ trick.createdDate | date('d/m/Y') }}
						à
						{{ trick.createdDate | date('h:m') }}
						par
						{{ trick.author.username }}
					</div>
					<div class="content">
						<p>{{ trick.description | raw }}</p>
						<a href="{{ path('trick_showOne', {'trickSlug':trick.slug}) }}" class="btn btn-primary">Lire la suite</a>
					</div>
				</div>
			</div>

		{% endfor %}
	</br>

	{% set path = 'trick_showByCategory' %}
	{% set param1 = {'categorySlug':categorySlug, 'page':currentPage-1} %}
	{% set param2 = {'categorySlug':categorySlug, 'page':currentPage} %}
	{% set param3 = {'categorySlug':categorySlug, 'page':currentPage+1} %}
	{% set totalOfPages = tricksPagination.totalOfPages %}
	{% set currentPage = currentPage %}
	{% include "_partials/_pagination.html.twig" %}

</div>{% endblock %}

templates/trick/showOne.html.twig
{% extends 'base.html.twig' %}
{% form_theme formComment 'bootstrap_5_layout.html.twig' %}
{% block title %}
	Un Trick
{% endblock %}

{% block body %}
	<section class="trick">
		<h2 class="metadata">
			{{ trick.name }}
		</h2>
		<div>
			Créé le
			{{ trick.createdDate| date('d/m/Y') }}
			à
			{{ trick.createdDate | date('h:m') }}
		</div>
		<div>
			{% if trick.categories %}
				{% for category in trick.categories %}
					<a href="{{ path('trick_showByCategory', {'categorySlug': category.slug}) }}">
						{{ category.name }}
					</a>
				{% endfor %}
			{% endif %}
		</div>
		<article>
			<div class="content">
				<p>
					{{ trick.description }}
				</p>
			</div>
		</article>
	</section>

	<section class="trick">
		<div class="content">
			{% if is_granted("TRICK_EDIT", trick) %}
				<a href="{{ path('trick_edit', {'slug':trick.slug}) }}" class="btn btn-warning">
					<i class="fas fa-edit"></i>
				</a>
			{% endif %}
			{% if is_granted("TRICK_DELETE", trick) %}
				<a href="{{ path('trick_delete', {'slug':trick.slug}) }}" class="btn btn-danger">
					<i class="fas fa-trash-alt"></i>
				</a>
			{% endif %}
		</div>
	</section>

	<section class="content">
		{% if is_granted('ROLE_USER') %}
			{{ form_start(formComment, {'attr': {'novalidate': 'novalidate'}}
			) }}
			{{ form_row(formComment.comment, {'attr' : {'placeholder' : "Salut, ..." }}
			) }}
			<button type="submit" class="btn btn-success">
				Enregistrer
			</button>
			{{ form_end(formComment) }}
		{% endif %}
	</section>

	<section>
		<div id="js-comments"></div>
	</section>
{% endblock %}

{% block javascripts %}
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
		var isAdmin = {{ is_granted('ROLE_ADMIN') ? 'true' : 'false' }};
		$(document).ready(function () {
			var page = 1;
			var morePages = true;
			var lastCalled = Date.now();
			loadComments(page);

			$(window).scroll(function () {
				if (($(window).scrollTop() + $(window).height() >= $(document).height() - 100) && morePages) {
					// Ajout d'un delai pour éviter les appels multiples à la fonction loadComments avec une seule action de scroll
					var now = Date.now();
					if (now - lastCalled > 150) {
						lastCalled = now;
						page++;
						loadComments(page);
					}
				}
			});
		});
		function loadComments(page) {
			$.ajax({
				type: 'GET',
				// #[Route('/trick/{trickSlug}/commentaires', name: 'trick_getComments', methods:["GET"])]
				url: '/trick/' + '{{ trickSlug }}' + '/commentaires?page=' + page,
				dataType: 'json',				
				success: function (data) {
					// On boucle une page :
					for (var i = 1; i <= data.commentsData.length; i++) {
						// data.commentsData.length = nombre de comments par page
						var date = new Date(data.commentsData[i].created_date);
						var dateFormatted = date.toLocaleDateString() + ' à ' + date.toLocaleTimeString("fr-FR", {hour: '2-digit', minute:'2-digit'});
						var com = $("<p>Ecrit le " + dateFormatted + " par " + data.commentsData[i].user.username + "</p>" + "<p>" + data.commentsData[i].comment + "</p>");

						// Ajout du bouton "supprimer" si Admin :
						if (isAdmin) {
							// #[Route('/commentaires/{comment_id}/{trick_slug}/supprimer', name: 'comment_delete')]
							var deleteBtn = $("<a>")
								.attr("href", "/commentaires/" + data.commentsData[i].id + "/" + "{{ trickSlug }}" + "/supprimer")
								.addClass("btn btn-danger")
								.text("Supprimer");

							$("#js-comments").append(com);
							$("#js-comments").append(deleteBtn);
						} else {
							$("#js-comments").append(com);
						}
					}
					if (page >= data.totalNumberOfPages) {
						morePages = false;
					}
				},
				error: function(xhr, status, error) {
					console.error('Erreur lors du chargement des commentaires : ' + error);
				}
			});
		};
	</script>
{% endblock %}

templates/trick/show_by_category.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ categorySlug }} {% endblock %}

{% block body %}
	<h2 style="margin: 30px;">
		Liste des Tricks de la catégorie
		<a href="{{ path('category_showOne', {'slug':categorySlug}) }}" title="Voir la définition de cette catégorie"> {{ categorySlug }} </a>
	</h2>
	<div class="row mt-4">
		{% if tricksPagination %}
		{% for trick in tricksPagination.tricksPerPage %}
			<div class="col-3 mb-3">
				<div class="card h-100">
					<div class="card-body">
						<h2 class="card-title text-truncate" style="font-size: 1.5rem; line-height: 1.2; margin-bottom: 10px;">{{ trick.name }}</h2>

						{% if trick.getImages() is not empty %}
							<img src="{{ asset('/uploads/images/' ~ trick.getImages() | first.name) }}" alt="Image" class="card-img-top">
						{% else %}
							{# <img src="{{ asset('/path/to/placeholder-image.jpg') }}" alt="Placeholder Image" class="card-img-top"> #}
						{% endif %}

						<p style="color: #8c959e; margin-bottom: 16px; margin-top: 10px;">
							<span style="margin-bottom: 1.5em;"><i class="fa fa-calendar"></i> {{ trick.createdDate| date('d/m/Y') }} à {{ trick.createdDate | date('h:m') }}</span>
							<span style="margin-bottom: 1.5em;"><img src="{{trick.author.avatar}}" class="rounded-circle" height="24" width="24"/> {{ trick.author.username }}</span>
						</p>

						<div style="margin-bottom: 16px;">
							{% if trick.categories %}
								{% for category in trick.categories %}
									<a href="{{ path('trick_showByCategory', {'categorySlug': category.slug}) }}" style="margin-right: 5px;">
										<i class="fa fa-tag"></i> {{ category.name }}
									</a>
								{% endfor %}
							{% endif %}
						</div>

						<div class="card-text text-truncate lire-suite">
							<p>{{ trick.description | raw }}</p>
							<a href="{{ path('trick_showOne', {'trickSlug':trick.slug}) }}" class="btn btn-primary btn-custom">Voir ce Trick</a>
						</div>

						<div style="color: #8c959e; margin-bottom: 10px; margin-top: 10px;">
							{{ trick.comments.count() }}
							{% if trick.comments.count() > 1 %} commentaires
							{% else %} commentaire
							{% endif %}
						</div>

					</div>
				</div>
			</div>
		{% endfor %}
		{% endif %}

	{% set path = 'trick_showByCategory' %}
	{% set param1 = {'categorySlug':categorySlug, 'page':currentPage-1} %}
	{% set param2 = {'categorySlug':categorySlug, 'page':currentPage} %}
	{% set param3 = {'categorySlug':categorySlug, 'page':currentPage+1} %}
	{% if tricksPagination %}{% set totalOfPages = tricksPagination.totalOfPages %}{% endif %}
	{% set currentPage = currentPage %}
	{% include "_partials/_pagination.html.twig" %}

	</div>
{% endblock %}